package main

// Purpose: HTTP client helpers for talking to the local ai plugin daemon
// (base URL resolution, generic request, GET). Inputs are a context, path,
// method, and body; outputs are the response bytes/status or an error.
// Constraints: split out of ai.go (CLI-R12) as a pure move, no behavior change.

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"

	"github.com/nself-org/nself-ai-cli/internal/httptimeout"
)

func aiPluginURL() string {
	if u := os.Getenv("PLUGIN_AI_INTERNAL_URL"); u != "" {
		return u
	}
	// plugin-ai listens on port 3709 (see plugins-pro/paid/ai/go/internal/config).
	// The default hostname matches the docker-compose service name generated by
	// `nself build`. Older templates incorrectly used "ai:3680" — set
	// PLUGIN_AI_INTERNAL_URL to override if your compose service is named
	// differently.
	return "http://plugin-ai:3709"
}

func aiPluginRequest(ctx context.Context, method, path string, body []byte) ([]byte, int, error) {
	var rdr io.Reader
	if body != nil {
		rdr = bytes.NewReader(body)
	}
	req, err := http.NewRequestWithContext(ctx, method, aiPluginURL()+path, rdr)
	if err != nil {
		return nil, 0, err
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if tok := os.Getenv("PLUGIN_INTERNAL_SECRET"); tok != "" {
		req.Header.Set("X-Internal-Token", tok)
	}
	resp, err := httptimeout.Default.Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	return b, resp.StatusCode, nil
}

func aiPluginGET(ctx context.Context, path string) ([]byte, error) {
	body, status, err := aiPluginRequest(ctx, "GET", path, nil)
	if err != nil {
		return nil, err
	}
	if status >= 400 {
		return nil, fmt.Errorf("plugin-ai %s %d: %s", path, status, string(body))
	}
	return body, nil
}

// -----------------------------------------------------------------------------
// init — wire commands + flags
// -----------------------------------------------------------------------------
