package federation

import (
	"bytes"
	"fmt"
	"text/template"
)

// apolloRouterPort is the CS_7 port for the Apollo Router service.
const apolloRouterPort = 4000

// routerComposeTemplate is the docker-compose service block for Apollo Router.
// It is injected as the CS_7 custom service when federation is enabled.
// The supergraph schema is mounted read-only from the host.
const routerComposeTemplate = `  apollo-router:
    image: ghcr.io/apollographql/router:v1.46.0
    restart: unless-stopped
    ports:
      - "127.0.0.1:{{.Port}}:4000"
    volumes:
      - {{.SupergraphPath}}:/dist/config/supergraph.graphql:ro
      - {{.RouterConfigPath}}:/dist/config/router.yaml:ro
    environment:
      APOLLO_ROUTER_SUPERGRAPH_PATH: /dist/config/supergraph.graphql
      APOLLO_ROUTER_CONFIG_PATH: /dist/config/router.yaml
    depends_on:
      hasura:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8088/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - nself_network
    labels:
      nself.service: apollo-router
      nself.cs_slot: CS_7
      nself.federation: "true"
`

// routerComposeData is the data struct for routerComposeTemplate.
type routerComposeData struct {
	Port             int
	SupergraphPath   string
	RouterConfigPath string
}

// RouterComposeOptions controls the Apollo Router service block generation.
type RouterComposeOptions struct {
	// SupergraphPath is the absolute host path to supergraph.graphql.
	SupergraphPath string
	// RouterConfigPath is the absolute host path to router.yaml base config.
	RouterConfigPath string
}

// ComposeService returns the docker-compose YAML block for the Apollo Router
// CS_7 service. The returned string is ready to be injected into the services:
// section of docker-compose.yml when NSELF_FEDERATION=true.
func ComposeService(opts RouterComposeOptions) (string, error) {
	if opts.SupergraphPath == "" {
		return "", fmt.Errorf("SupergraphPath must not be empty")
	}
	if opts.RouterConfigPath == "" {
		return "", fmt.Errorf("RouterConfigPath must not be empty")
	}
	tmpl, err := template.New("router").Parse(routerComposeTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing router compose template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, routerComposeData{
		Port:             apolloRouterPort,
		SupergraphPath:   opts.SupergraphPath,
		RouterConfigPath: opts.RouterConfigPath,
	}); err != nil {
		return "", fmt.Errorf("rendering router compose block: %w", err)
	}
	return buf.String(), nil
}

// NginxDirective returns the nginx upstream + location block to redirect
// /graphql traffic to Apollo Router (port 4000) when federation is enabled,
// or to Hasura (port 8080) when disabled.
//
// federationEnabled should mirror the NSELF_FEDERATION env var.
func NginxDirective(federationEnabled bool) string {
	if federationEnabled {
		return fmt.Sprintf(`
  # GraphQL — Apollo Router (federation enabled, CS_7)
  location /v1/graphql {
    proxy_pass http://127.0.0.1:%d;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
`, apolloRouterPort)
	}
	return `
  # GraphQL — Hasura (federation disabled, default)
  location /v1/graphql {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
`
}

// RouterBaseConfig returns the base Apollo Router YAML configuration content.
// This is written to .nself/federation/router.yaml and mounted into the
// Apollo Router container.
func RouterBaseConfig() string {
	return `# Apollo Router base configuration
# Generated by nself build — do not hand-edit
# Add router.yaml.d/ fragments for custom configuration overrides.

supergraph:
  listen: 0.0.0.0:4000

health_check:
  listen: 0.0.0.0:8088
  path: /health

sandbox:
  enabled: false

homepage:
  enabled: false

include_subgraph_errors:
  all: false

traffic_shaping:
  router:
    timeout: 30s
  all:
    timeout: 25s
`
}
