/**
 * VPN Provider Factory
 * Central registry for all VPN provider implementations
 */

import { IVPNProvider, VPNProvider } from '../types.js';
import { NordVPNProvider } from './nordvpn.js';
import { PIAProvider } from './pia.js';
import { MullvadProvider } from './mullvad.js';
import { SurfsharkProvider } from './surfshark.js';
import { ExpressVPNProvider } from './expressvpn.js';
import { ProtonVPNProvider } from './protonvpn.js';
import { KeepSolidProvider } from './keepsolid.js';
import { CyberGhostProvider } from './cyberghost.js';
import { AirVPNProvider } from './airvpn.js';
import { WindscribeProvider } from './windscribe.js';
import { createLogger } from '@nself/plugin-utils';

const logger = createLogger('vpn:providers');

// Provider registry
const providers: Map<VPNProvider, () => IVPNProvider> = new Map();

// Register implemented providers
providers.set('nordvpn', () => new NordVPNProvider());
providers.set('pia', () => new PIAProvider());
providers.set('mullvad', () => new MullvadProvider());
providers.set('surfshark', () => new SurfsharkProvider());
providers.set('expressvpn', () => new ExpressVPNProvider());
providers.set('protonvpn', () => new ProtonVPNProvider());
providers.set('keepsolid', () => new KeepSolidProvider());
providers.set('cyberghost', () => new CyberGhostProvider());
providers.set('airvpn', () => new AirVPNProvider());
providers.set('windscribe', () => new WindscribeProvider());

/**
 * Get provider instance by name
 */
export function getProvider(name: VPNProvider): IVPNProvider {
  const factory = providers.get(name);

  if (!factory) {
    throw new Error(
      `Provider '${name}' not implemented. Available providers: ${Array.from(providers.keys()).join(', ')}`
    );
  }

  return factory();
}

/**
 * Check if provider is supported
 */
export function isProviderSupported(name: string): name is VPNProvider {
  return providers.has(name as VPNProvider);
}

/**
 * Get list of all supported providers
 */
export function getSupportedProviders(): VPNProvider[] {
  return Array.from(providers.keys());
}

/**
 * Provider metadata for documentation
 */
export const providerMetadata: Record<
  VPNProvider,
  {
    name: string;
    cliRequired: boolean;
    portForwarding: boolean;
    p2pServers: string;
    notes: string;
  }
> = {
  nordvpn: {
    name: 'NordVPN',
    cliRequired: true,
    portForwarding: false,
    p2pServers: '5,500+ servers in 47 countries',
    notes: 'Requires nordvpn CLI. Install from https://nordvpn.com/download/linux/',
  },
  pia: {
    name: 'Private Internet Access',
    cliRequired: false,
    portForwarding: true,
    p2pServers: 'All servers (port forwarding on all except US)',
    notes: 'Port forwarding supported on most servers. Best for torrenting.',
  },
  mullvad: {
    name: 'Mullvad',
    cliRequired: true,
    portForwarding: false,
    p2pServers: 'All 674 servers support P2P',
    notes: 'Port forwarding removed July 2023. Strong privacy focus. Account number-based.',
  },
  surfshark: {
    name: 'Surfshark',
    cliRequired: true,
    portForwarding: false,
    p2pServers: 'P2P-specific servers in 100+ locations',
    notes: 'Requires surfshark-vpn CLI. Unlimited simultaneous connections.',
  },
  expressvpn: {
    name: 'ExpressVPN',
    cliRequired: true,
    portForwarding: false,
    p2pServers: 'All 3,000+ servers support P2P',
    notes: 'Requires expressvpn CLI and activation code. Lightway (UDP/TCP) protocol.',
  },
  protonvpn: {
    name: 'ProtonVPN',
    cliRequired: true,
    portForwarding: false,
    p2pServers: 'Plus-tier servers in 40+ countries',
    notes:
      'Requires protonvpn-cli. Free tier available (limited servers). Secure Core and Tor support.',
  },
  keepsolid: {
    name: 'KeepSolid VPN Unlimited',
    cliRequired: false,
    portForwarding: false,
    p2pServers: 'P2P-specific servers available',
    notes:
      'API-only — no official Linux CLI. Uses WireGuard or OpenVPN config files generated by API.',
  },
  cyberghost: {
    name: 'CyberGhost VPN',
    cliRequired: false,
    portForwarding: false,
    p2pServers: 'P2P-specific servers in 50+ countries',
    notes:
      'Config-file-based via OpenVPN or WireGuard. Requires openvpn or wg-quick installed.',
  },
  airvpn: {
    name: 'AirVPN',
    cliRequired: false,
    portForwarding: true,
    p2pServers: 'All servers support P2P',
    notes:
      'Config-file-based via OpenVPN or WireGuard. Port forwarding supported. Requires API key.',
  },
  windscribe: {
    name: 'Windscribe',
    cliRequired: true,
    portForwarding: true,
    p2pServers: 'P2P-flagged servers in 60+ countries',
    notes:
      'Requires windscribe CLI. Free tier (10GB/month). Port forwarding via Ephemeral Port feature.',
  },
};

logger.info(`Provider factory initialized with ${providers.size} providers`);

export { BaseVPNProvider } from './base.js';
export { NordVPNProvider } from './nordvpn.js';
export { PIAProvider } from './pia.js';
export { MullvadProvider } from './mullvad.js';
export { SurfsharkProvider } from './surfshark.js';
export { ExpressVPNProvider } from './expressvpn.js';
export { ProtonVPNProvider } from './protonvpn.js';
export { KeepSolidProvider } from './keepsolid.js';
export { CyberGhostProvider } from './cyberghost.js';
export { AirVPNProvider } from './airvpn.js';
export { WindscribeProvider } from './windscribe.js';
