-- Down migration paired with 001_siem_tables.sql (P99 1.11 T07 autogenerated)
-- Rollback for 001_siem_tables.sql
-- Idempotent (IF EXISTS guards). Drops the ship log first (FK references destinations).

DROP INDEX IF EXISTS idx_siem_destinations_tenant;
DROP INDEX IF EXISTS idx_siem_ship_log_dest;

DROP TABLE IF EXISTS np_siem_ship_log;
DROP TABLE IF EXISTS np_siem_destinations;
