// Package render turns contract:cli.proxy-routes v1 into Traefik file-provider
// dynamic configuration (ADR 0027: file provider only, no Docker socket, no ACME
// resolver; certificates are core-issued and read from ssl/).
//
// Inputs: a contract.Model and Options. Output: dynamic.yml bytes, deterministic
// for equal inputs. Any model value the renderer cannot express (non-empty
// unmodelled/shadowed_by/unmodelled_global, an inexpressible field value) makes
// Render return a RefusalError naming the route and field; nothing is produced.
package render

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/nself-org/plugins/free/traefik/internal/contract"
)

// Options locate the inputs the renderer cannot take from routes.json.
type Options struct {
	SSLRoot  string // ssl/ as the renderer sees it (certificates/<dir> may be a generation link)
	CertRoot string // the same tree as Traefik sees it; certFile/keyFile paths start here (default SSLRoot)
	Helper   string // base URL of traefik-acme (default http://traefik-acme:8080)
}

type listener struct {
	entry, tag, opt string
	secure          bool
}

type builder struct {
	m                                         *contract.Model
	o                                         Options
	routers, services, mws, transports, tlsOp map[string]any
	certs                                     map[string][2]string
	zones                                     map[string]contract.Zone
	refs                                      []Refusal
	hasTLS                                    bool
	cur                                       string            // id of the route being rendered ("-" for globals)
	hosts                                     map[string]string // entrypoint|server name -> route id
	tier                                      int               // host specificity added to every router priority of the route
	noLog                                     bool              // the location under render has access_log off
}

var unsafeRE = regexp.MustCompile(`[^A-Za-z0-9]+`)

func safe(s string) string { return strings.Trim(unsafeRE.ReplaceAllString(s, "-"), "-") }

func h8(v any) string {
	j, _ := json.Marshal(v)
	s := sha256.Sum256(j)
	return hex.EncodeToString(s[:4])
}

func (b *builder) refuse(route, field, reason string) {
	b.refs = append(b.refs, Refusal{Route: route, Field: field, Reason: reason})
}

// Render produces dynamic.yml for m, or a *RefusalError.
func Render(m *contract.Model, o Options) ([]byte, error) {
	if o.Helper == "" {
		o.Helper = "http://traefik-acme:8080"
	}
	if o.CertRoot == "" {
		o.CertRoot = o.SSLRoot
	}
	b := &builder{m: m, o: o, routers: map[string]any{}, services: map[string]any{}, mws: map[string]any{},
		transports: map[string]any{}, tlsOp: map[string]any{}, certs: map[string][2]string{}, zones: map[string]contract.Zone{}, cur: "-", hosts: map[string]string{}}
	for _, z := range m.Zones {
		b.zones[z.Name] = z
	}
	if len(m.UnmodelledGlobal) > 0 {
		b.refuse("-", "unmodelled_global", fmt.Sprintf("%d http-level directive(s), first: %q", len(m.UnmodelledGlobal), m.UnmodelledGlobal[0]))
	}
	if m.Defaults.MaxBodyBytes < 0 {
		b.refuse("-", "defaults.max_body_bytes", fmt.Sprintf("%d is negative", m.Defaults.MaxBodyBytes))
	}
	for _, r := range m.Routes {
		b.route(r)
	}
	b.cur, b.tier, b.noLog = "-", 0, false
	b.defaultServer()
	if len(b.refs) > 0 {
		sort.SliceStable(b.refs, func(i, j int) bool {
			if b.refs[i].Route != b.refs[j].Route {
				return b.refs[i].Route < b.refs[j].Route
			}
			return b.refs[i].Field < b.refs[j].Field
		})
		return nil, &RefusalError{Items: b.refs}
	}
	return b.document()
}

func (b *builder) document() ([]byte, error) {
	httpSec := map[string]any{}
	for k, v := range map[string]map[string]any{"routers": b.routers, "services": b.services, "middlewares": b.mws, "serversTransports": b.transports} {
		if len(v) > 0 {
			httpSec[k] = v
		}
	}
	doc := map[string]any{"http": httpSec}
	tlsSec := map[string]any{}
	if len(b.tlsOp) > 0 {
		tlsSec["options"] = b.tlsOp
	}
	if len(b.certs) > 0 {
		dirs := make([]string, 0, len(b.certs))
		for d := range b.certs {
			dirs = append(dirs, d)
		}
		sort.Strings(dirs)
		var list []any
		for _, d := range dirs {
			list = append(list, map[string]any{"certFile": b.certs[d][0], "keyFile": b.certs[d][1], "stores": []string{"default"}})
		}
		tlsSec["certificates"] = list
		tlsSec["stores"] = map[string]any{"default": map[string]any{"defaultCertificate": map[string]any{"certFile": b.certs[dirs[0]][0], "keyFile": b.certs[dirs[0]][1]}}}
	}
	if len(tlsSec) > 0 {
		doc["tls"] = tlsSec
	}
	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, err
	}
	head := "# GENERATED BY nself traefik renderer - DO NOT HAND EDIT\n" +
		"# Source: contract:cli.proxy-routes v1 (project " + m1(b.m.Project) + ", env " + m1(b.m.Env) + "). Certificates come from ssl/ (ADR 0026/0027).\n" +
		"# Known equivalences: upstream https is not verified (nginx default); OCSP stapling and DHE suites have no Traefik equivalent.\n"
	return append([]byte(head), out...), nil
}

func m1(s string) string { return strings.ReplaceAll(strings.ReplaceAll(s, "\n", " "), "\r", " ") }

// mw registers a middleware once, named by kind and content hash, and returns its name.
func (b *builder) mw(kind string, spec any) string {
	name := kind + "-" + h8(spec)
	b.put(b.mws, "middleware", name, map[string]any{kind: spec}, false)
	return name
}

func (b *builder) addRouter(name, rule string, pri int, l listener, mws []string, svc string) {
	spec := map[string]any{"rule": rule, "entryPoints": []string{l.entry}, "service": svc, "priority": pri + b.tier}
	if b.noLog {
		spec["observability"] = map[string]any{"accessLogs": false}
	}
	if len(mws) > 0 {
		spec["middlewares"] = mws
	}
	if l.secure {
		t := map[string]any{}
		if l.opt != "" {
			t["options"] = l.opt
		}
		spec["tls"] = t
	}
	b.put(b.routers, "router", name+"-"+l.tag, spec, true)
}

func (b *builder) route(r contract.Route) {
	b.cur, b.tier = r.ID, hostTier(r)
	if len(r.Unmodelled) > 0 {
		b.refuse(r.ID, "unmodelled", fmt.Sprintf("%d directive(s) outside the closed vocabulary, first: %q", len(r.Unmodelled), r.Unmodelled[0]))
	}
	if r.ShadowedBy != nil {
		b.refuse(r.ID, "shadowed_by", "suppressed by hand-managed "+*r.ShadowedBy)
	}
	host, ok := b.hostRule(r)
	if !ok || len(r.Unmodelled) > 0 || r.ShadowedBy != nil {
		return
	}
	ls := b.listeners(r)
	if !b.hostsFree(r, ls) {
		return
	}
	sec := ""
	if len(r.SecurityHeaders) > 0 {
		hdr := map[string]string{}
		for k, v := range r.SecurityHeaders {
			if strings.Contains(v, "$") {
				b.refuse(r.ID, "security_headers."+k, "value holds an nginx variable")
			}
			if !headerOK(k, v) {
				b.refuse(r.ID, "security_headers."+k, "header name is not a token or the value holds a control character")
			}
			hdr[k] = v
		}
		sec = b.mw("headers", map[string]any{"customResponseHeaders": hdr})
	}
	for i, l := range r.Locations {
		b.location(r, i, l, host, ls, sec)
	}
	b.blocked(r, host, ls, sec)
	if r.HTTPToHTTPSRedirect && r.Listen.HTTP {
		for _, l := range ls {
			if !l.secure {
				b.addRouter(rname(r.ID)+"-redirect", host+" && PathPrefix(`/`)", 200000, l, []string{b.redirectMW(r.ID, "http_to_https_redirect", 301)}, b.responder())
			}
		}
	}
}

// hostsFree refuses a server name that another route already serves on the same
// entrypoint: Traefik would pick one of two equal rules at random, nginx keeps
// the first and warns. It also refuses a custom TLS option on a wildcard name,
// because Traefik selects TLS options by SNI from Host() rules only.
func (b *builder) hostsFree(r contract.Route, ls []listener) bool {
	ok := true
	for _, l := range ls {
		for _, n := range r.ServerNames {
			key := l.entry + "|" + n
			if prev, dup := b.hosts[key]; dup && prev != r.ID {
				b.refuse(r.ID, "server_names", fmt.Sprintf("%q on %s is already served by route %s", n, l.entry, prev))
				ok = false
			}
			b.hosts[key] = r.ID
			if l.opt != "" && !nameRE.MatchString(n) {
				b.refuse(r.ID, "tls", fmt.Sprintf("wildcard %q with non-default protocols or ciphers: Traefik picks TLS options by SNI from Host() rules only", n))
				ok = false
			}
		}
	}
	return ok
}

func (b *builder) listeners(r contract.Route) []listener {
	var ls []listener
	if !r.Listen.HTTP && !r.Listen.HTTPS {
		b.refuse(r.ID, "listen", "neither http nor https (nginx would listen on *:80); the route is not guessed")
	}
	if r.Listen.HTTP {
		ls = append(ls, listener{entry: "web", tag: "web"})
	}
	if r.Listen.HTTPS {
		opt, ok := b.tlsFor(r)
		if ok {
			ls = append(ls, listener{entry: "websecure", tag: "tls", opt: opt, secure: true})
		}
	}
	return ls
}

var wildRE = regexp.MustCompile(`^\*\.[A-Za-z0-9.-]+$`)
var nameRE = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9.-]*$`)

// dotRE is nginx's ".example.test": the name itself plus every subdomain.
var dotRE = regexp.MustCompile(`^\.[A-Za-z0-9][A-Za-z0-9.-]*$`)

// tierExact outranks every wildcard route: nginx picks the server by exact name
// before any wildcard, and only then the location, so path length must never let a
// wildcard route's location beat an exact host. Larger than the biggest location
// priority, smaller than the 200000 redirect.
const tierExact = 100000

// hostTier is tierExact when every server name is a plain name.
func hostTier(r contract.Route) int {
	if len(r.ServerNames) == 0 {
		return 0
	}
	for _, n := range r.ServerNames {
		if !nameRE.MatchString(n) {
			return 0
		}
	}
	return tierExact
}

func (b *builder) hostRule(r contract.Route) (string, bool) {
	if len(r.ServerNames) == 0 {
		b.refuse(r.ID, "server_names", "empty")
		return "", false
	}
	var parts []string
	for _, n := range r.ServerNames {
		switch {
		case nameRE.MatchString(n):
			parts = append(parts, "Host(`"+n+"`)")
		case dotRE.MatchString(n):
			parts = append(parts, "Host(`"+n[1:]+"`)", "HostRegexp(`^.+"+regexp.QuoteMeta(n)+"$`)")
		case wildRE.MatchString(n):
			parts = append(parts, "HostRegexp(`^.+"+regexp.QuoteMeta(n[1:])+"$`)")
		default:
			b.refuse(r.ID, "server_names", fmt.Sprintf("%q is not a plain or leading-wildcard name", n))
			return "", false
		}
	}
	if len(parts) == 1 {
		return parts[0], true
	}
	return "(" + strings.Join(parts, " || ") + ")", true
}
