#!/usr/bin/env bash
# parity.sh: request-level parity between nginx (the cli golden confs) and Traefik (rendered dynamic.yml) on the
# shared fixtures, in Linux containers (P7-DEPL-02, ADR 0015/0027). The workflow runs this same script.
# Per fixture: render, start nginx + traefik + traefik-acme + one backend serving every upstream, require every
# Traefik router/service/middleware enabled, then run the request matrix (tests/ptool). tls-full also proves that a
# new certificate generation changes the parsed config and is served after a reload.
# Needs docker and jq. Work files live in $PARITY_WORK (default: .parity-work next to this plugin) and are removed.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd); PLUGIN=$(dirname "$HERE"); REPO=$(cd "$PLUGIN/../.." && pwd)
WORK=${PARITY_WORK:-$PLUGIN/.parity-work}/$$; mkdir -p "$WORK"
NGINX_IMG=nginx:1.29-alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de
TRAEFIK_IMG=$(jq -r .image "$REPO/images.d/traefik.json")
NET=nself-traefik-parity-$$; PTOOL=nself-traefik-ptool:p$$; RENDER=nself-traefik-render:p$$; LABEL=nself-parity=$$
ME="$(id -u):$(id -g)"
FIXTURES=${PARITY_FIXTURES:-"http-full tls-full plugin-modelled host-tier"}
cleanup() {
  for c in $(docker ps -aq --filter "label=$LABEL"); do docker rm -f "$c" >/dev/null 2>&1 || true; done
  docker network rm "$NET" >/dev/null 2>&1 || true
  docker rmi -f "$PTOOL" "$RENDER" >/dev/null 2>&1 || true
  rm -rf "$WORK"
}
trap cleanup EXIT
log() { printf '== %s\n' "$*"; }
ptool() { docker run --rm --network "$NET" --label "$LABEL" "$@"; }

log "build images"
docker build -q -t "$RENDER" "$PLUGIN" >/dev/null
docker build -q -t "$PTOOL" -f "$HERE/Dockerfile.ptool" "$PLUGIN" >/dev/null
docker network create "$NET" >/dev/null

render() { # render <fixture dir> <work dir>
  docker run --rm --user "$ME" --label "$LABEL" -v "$1/routes.json:/nself/routes.json:ro" -v "$2/ssl:/nself/ssl:ro" \
    -v "$2/dynamic:/dynamic" "$RENDER" --routes /nself/routes.json --out /dynamic --ssl /nself/ssl
}

for f in $FIXTURES; do
  log "fixture $f"
  F=$PLUGIN/testdata/fixtures/$f; D=$WORK/$f; mkdir -p "$D/ssl" "$D/dynamic"
  docker run --rm --user "$ME" --label "$LABEL" -v "$F/routes.json:/routes.json:ro" -v "$D/ssl:/ssl" "$PTOOL" gencert --routes /routes.json --out /ssl
  render "$F" "$D"
  grep -q '^http:' "$D/dynamic/dynamic.yml"

  # sites/api-docs.conf is generated by nself build but is not in routes.json (an alias of a host file, always TLS):
  # a contract gap recorded in the Ticket handoff. It cannot run in a container, so the reference tree omits it.
  mkdir -p "$D/sites"; cp "$F"/nginx/sites/*.conf "$D/sites/"; rm -f "$D/sites/api-docs.conf"
  aliases=(); for a in $(docker run --rm --label "$LABEL" -v "$F/routes.json:/routes.json:ro" "$PTOOL" plan --routes /routes.json | awk '$1=="alias"{print $2}'); do aliases+=(--network-alias "$a"); done
  docker run -d --name backend --label "$LABEL" --network "$NET" --network-alias backend "${aliases[@]}" -v "$F/routes.json:/routes.json:ro" "$PTOOL" backend --routes /routes.json >/dev/null
  docker run -d --name nginx --label "$LABEL" --network "$NET" \
    -v "$F/nginx/nginx.conf:/etc/nginx/nginx.conf:ro" -v "$F/nginx/includes:/etc/nginx/includes:ro" \
    -v "$F/nginx/conf.d:/etc/nginx/conf.d:ro" -v "$D/sites:/etc/nginx/sites:ro" -v "$D/ssl:/etc/nginx/ssl:ro" "$NGINX_IMG" >/dev/null
  docker run -d --name traefik-acme --label "$LABEL" --network "$NET" --user "$ME" -v "$D/ssl/.acme-webroot:/acme-webroot:ro" \
    "$RENDER" serve-static --root /acme-webroot --listen :8080 >/dev/null
  docker run -d --name traefik --label "$LABEL" --network "$NET" -v "$HERE/traefik-test.yml:/etc/traefik/traefik.yml:ro" \
    -v "$D/dynamic:/dynamic:ro" -v "$D/ssl:/nself/ssl:ro" "$TRAEFIK_IMG" >/dev/null

  ok=0
  for _ in $(seq 1 40); do
    if ptool "$PTOOL" rawdata --require default-root-web@file --url http://traefik:8082/api/rawdata >"$WORK/rawdata.out" 2>&1; then ok=1; break; fi
    sleep 1
  done
  cat "$WORK/rawdata.out"
  [ "$ok" = 1 ] || { docker logs traefik 2>&1 | tail -30; echo "traefik never reported every router and service enabled"; exit 1; }
  docker exec nginx nginx -t 2>&1 | tail -2 || { docker logs nginx 2>&1 | tail -20; exit 1; }
  sleep 2
  tier=(); [ "$f" = host-tier ] && tier=(--need-tier)
  ptool -v "$F/routes.json:/routes.json:ro" "$PTOOL" matrix --routes /routes.json --nginx nginx --traefik traefik "${tier[@]}"

  if [ "$f" = http-full ]; then
    log "timeouts: websocket idle 75s, partial headers closed at 60s, trickle uploads (Traefik readTimeout is a total deadline)"
    # name:ptool args. A 40s upload passes on both; an 80s one passes on nginx (it times each gap) and is cut by Traefik (accepted).
    for T in nginx traefik; do
      cut=ok; [ "$T" = traefik ] && cut=cut
      for spec in "idle-$T:wsidle --secs 75" "up40-$T:slowpost --secs 40 --expect ok" "up80-$T:slowpost --secs 80 --expect $cut" \
        "hdr-idle-$T:slowheader --mode idle" "hdr-trickle-$T:slowheader --mode trickle"; do
        # shellcheck disable=SC2086
        docker run -d --name "${spec%%:*}" --label "$LABEL" --network "$NET" -v "$F/routes.json:/routes.json:ro" "$PTOOL" ${spec#*:} --routes /routes.json --target "$T" >/dev/null
      done
    done
    for T in nginx traefik; do
      for n in idle up40 up80 hdr-idle hdr-trickle; do
        rc=$(docker wait "$n-$T"); docker logs "$n-$T" 2>&1
        [ "$rc" = 0 ] || { echo "FAIL: $n via $T (timeouts differ from the documented behaviour)"; exit 1; }
        docker rm -f "$n-$T" >/dev/null
      done
    done
  fi

  log "per-client connection limit (two source addresses)"
  for T in nginx traefik; do
    docker run -d --name "hold-$T" --label "$LABEL" --network "$NET" -v "$F/routes.json:/routes.json:ro" "$PTOOL" connhold --routes /routes.json --target "$T" --secs 40 >/dev/null
    # Capture the log first: "docker logs | grep -q" under pipefail fails at random (grep exits early, docker logs gets SIGPIPE).
    for _ in $(seq 1 30); do
      hold=$(docker logs "hold-$T" 2>&1 || true)
      grep -qE '^(HELD|SKIP)' <<<"$hold" && break
      [ "$(docker inspect -f '{{.State.Running}}' "hold-$T")" = true ] || break
      sleep 1
    done
    hold=$(docker logs "hold-$T" 2>&1 || true)
    printf '%s\n' "$hold"
    grep -q '^HELD' <<<"$hold" || { echo "FAIL: client A did not hold the connection limit on $T"; exit 1; }
    grep -q '^A over limit: 429$' <<<"$hold" || { echo "FAIL: client A was not limited on $T"; exit 1; }
    ptool -v "$F/routes.json:/routes.json:ro" "$PTOOL" connprobe --routes /routes.json --target "$T"
    docker rm -f "hold-$T" >/dev/null
  done

  if [ "$f" = tls-full ]; then
    log "certificate generation switch"
    sni=$(jq -r '.routes[] | select(.tls) | .server_names[0]' "$F/routes.json" | head -1)
    before=$(ptool "$PTOOL" serial --addr traefik:443 --sni "$sni")
    reloads=$(docker logs traefik 2>&1 | grep -c 'Configuration received' || true)
    cp "$D/dynamic/dynamic.yml" "$WORK/dynamic.before"
    docker run --rm --user "$ME" --label "$LABEL" -v "$F/routes.json:/routes.json:ro" -v "$D/ssl:/ssl" "$PTOOL" gencert --routes /routes.json --out /ssl --gen 2
    render "$F" "$D"
    if cmp -s "$WORK/dynamic.before" "$D/dynamic/dynamic.yml"; then echo "FAIL: a new generation left dynamic.yml unchanged"; exit 1; fi
    grep -q '\.gen-2/' "$D/dynamic/dynamic.yml" || { echo "FAIL: dynamic.yml does not point at gen-2"; exit 1; }
    after=$before
    for _ in $(seq 1 30); do
      after=$(ptool "$PTOOL" serial --addr traefik:443 --sni "$sni"); [ "$after" != "$before" ] && break; sleep 1
    done
    now=$(docker logs traefik 2>&1 | grep -c 'Configuration received' || true)
    echo "served serial $before -> $after; provider reload log lines $reloads -> $now"
    [ "$after" != "$before" ] && [ "$now" -gt "$reloads" ] || { echo "FAIL: Traefik did not reload the new generation"; exit 1; }
  fi
  for c in nginx traefik traefik-acme backend; do docker rm -f "$c" >/dev/null; done
done
log "parity: all fixtures passed"
