"""Tests for scripts/ci/check-file-size.py (final gate G11, P7-HYG-42).

Each case builds a throwaway git repo, stages fixtures and runs the script there.
Runs under unittest (no third-party packages) and under pytest.
"""
import os
import subprocess
import sys
import tempfile
import unittest

SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                      "check-file-size.py")
BUDGET = ".github/file-size-budget.txt"


def body(n, first=""):
    """n newline-terminated lines, the first one optionally replaced."""
    lines = ["package zz"] * n
    if first and n:
        lines[0] = first
    return "\n".join(lines) + ("\n" if n else "")


class CheckFileSize(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.repo = self._tmp.name
        subprocess.run(["git", "init", "-q", self.repo], check=True)

    def tearDown(self):
        self._tmp.cleanup()

    def put(self, path, text, stage=True):
        full = os.path.join(self.repo, path)
        os.makedirs(os.path.dirname(full) or self.repo, exist_ok=True)
        with open(full, "wb") as fh:
            fh.write(text.encode() if isinstance(text, str) else text)
        if stage:
            subprocess.run(["git", "add", "-f", "--", path], cwd=self.repo, check=True)

    def budget(self, rows):
        text = "".join("%s\t%d\n" % (p, n) for p, n in sorted(rows.items()))
        self.put(BUDGET, text, stage=False)

    def run_check(self, *args):
        proc = subprocess.run([sys.executable, SCRIPT] + list(args), cwd=self.repo,
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return proc.returncode, proc.stdout.decode(), proc.stderr.decode()

    def read_budget(self):
        with open(os.path.join(self.repo, BUDGET)) as fh:
            return fh.read()

    def test_file_at_limit_passes(self):
        self.put("a/ok.go", body(300))
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_file_over_limit_fails_with_message(self):
        self.put("a/big.go", body(301))
        rc, out, _ = self.run_check()
        self.assertEqual((rc, out.strip()), (1, "a/big.go: 301 lines (limit 300)"))

    def test_unterminated_last_line_counts(self):
        self.put("a/x.go", body(300) + "package zz")
        rc, out, _ = self.run_check()
        self.assertEqual((rc, out.strip()), (1, "a/x.go: 301 lines (limit 300)"))

    def test_listed_at_exact_count_passes(self):
        self.put("a/big.go", body(350))
        self.budget({"a/big.go": 350})
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_listed_file_grown_by_one_fails(self):
        self.put("a/big.go", body(351))
        self.budget({"a/big.go": 350})
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertEqual(out.strip(), "a/big.go: 351 lines (budget 350, limit 300)")

    def test_listed_file_shrunk_but_over_fails_until_lowered(self):
        self.put("a/big.go", body(340))
        self.budget({"a/big.go": 350})
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertIn("a/big.go: stale budget row", out)
        self.assertIn("lower the row to 340", out)

    def test_listed_file_fell_to_limit_fails_as_stale(self):
        self.put("a/big.go", body(300))
        self.budget({"a/big.go": 350})
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertIn("a/big.go: stale budget row, 300 lines", out)

    def test_listed_file_gone_fails_as_stale(self):
        self.put("a/ok.go", body(3))
        self.budget({"a/gone.go": 400})
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertIn("a/gone.go: stale budget row, gone or not counted", out)

    def test_ignored_kinds_over_limit_pass(self):
        for path in ("a/x_test.go", "a/x.test.ts", "a/x.spec.js", "vendor/v.go",
                     "a/vendor/v.go", "a/testdata/t.go", "tests/t.py", "a/tests/t.sh"):
            self.put(path, body(400))
        self.put("a/gen.go", body(400, first="// GENERATED BY tool. DO NOT HAND EDIT"))
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_generated_mark_after_400_bytes_still_counts(self):
        self.put("a/late.go", "x" * 500 + "\n// GENERATED BY tool\n" + body(400))
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertIn("a/late.go: ", out)

    def test_non_source_extension_ignored(self):
        self.put("docs/big.md", "line\n" * 500)
        self.put("data/big.json", "{}\n" * 500)
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_every_source_extension_is_counted(self):
        exts = (".go", ".ts", ".tsx", ".js", ".mjs", ".py", ".rs", ".sh", ".astro")
        for ext in exts:
            self.put("src/f" + ext, body(301))
        rc, out, _ = self.run_check()
        self.assertEqual(rc, 1)
        self.assertEqual(len(out.strip().splitlines()), len(exts))

    def test_untracked_big_file_ignored(self):
        self.put("a/ok.go", body(3))
        self.put("a/untracked.go", body(400), stage=False)
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_list_mode_ignores_budget(self):
        self.put("a/big.go", body(350))
        self.put("b/ok.go", body(10))
        self.budget({"a/big.go": 350})
        rc, out, _ = self.run_check("--list")
        self.assertEqual((rc, out), (0, "a/big.go\t350\n"))

    def test_write_budget_seeds_sorted(self):
        self.put("b/z.go", body(310))
        self.put("a/y.go", body(305))
        self.put("c/ok.go", body(5))
        self.assertEqual(self.run_check("--write-budget")[0], 0)
        self.assertEqual(self.read_budget(), "a/y.go\t305\nb/z.go\t310\n")
        self.assertEqual(self.run_check()[:2], (0, ""))

    def test_write_budget_lowers_and_drops_only(self):
        self.put("a/shrunk.go", body(320))
        self.put("a/fixed.go", body(100))
        self.put("a/same.go", body(310))
        self.budget({"a/shrunk.go": 350, "a/fixed.go": 400, "a/same.go": 310})
        self.assertEqual(self.run_check("--write-budget")[0], 0)
        self.assertEqual(self.read_budget(), "a/same.go\t310\na/shrunk.go\t320\n")

    def test_write_budget_refuses_new_row_and_growth(self):
        self.put("a/grown.go", body(351))
        self.put("a/new.go", body(400))
        self.budget({"a/grown.go": 350})
        before = self.read_budget()
        rc, out, _ = self.run_check("--write-budget")
        self.assertEqual(rc, 1)
        self.assertIn("a/new.go: 400 lines (limit 300)", out)
        self.assertIn("a/grown.go: 351 lines (budget 350, limit 300)", out)
        self.assertEqual(self.read_budget(), before)

    def test_malformed_budget_is_exit_2(self):
        self.put("a/ok.go", body(3))
        self.put(BUDGET, "a/ok.go 350\n", stage=False)
        self.assertEqual(self.run_check()[0], 2)

    def test_path_with_spaces(self):
        self.put("dir one/big file.go", body(301))
        rc, out, _ = self.run_check()
        self.assertEqual((rc, out.strip()), (1, "dir one/big file.go: 301 lines (limit 300)"))


if __name__ == "__main__":
    unittest.main()
