// Command render is the traefik plugin's single binary.
//
//	render --routes routes.json --out DIR [--ssl DIR] [--cert-root DIR] [--helper URL]
//	render serve-static --root DIR --listen :8080
//	render healthcheck --addr 127.0.0.1:8080
//
// render reads contract:cli.proxy-routes v1 and writes DIR/dynamic.yml (atomic:
// temp file plus rename) and DIR/.nself-generated. Exit 0 ok, 1 refusal or
// invalid input (nothing is written), 2 I/O error.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"

	"github.com/nself-org/plugins/free/traefik/internal/contract"
	"github.com/nself-org/plugins/free/traefik/internal/render"
	"github.com/nself-org/plugins/free/traefik/internal/static"
)

const marker = "GENERATED BY nself traefik renderer - DO NOT HAND EDIT\n"

func main() { os.Exit(run(os.Args[1:], os.Stderr)) }

func run(args []string, errw io.Writer) int {
	if len(args) > 0 && args[0] == "serve-static" {
		return serve(args[1:], errw)
	}
	if len(args) > 0 && args[0] == "healthcheck" {
		return health(args[1:], errw)
	}
	fs := flag.NewFlagSet("render", flag.ContinueOnError)
	fs.SetOutput(errw)
	routes := fs.String("routes", "/nself/routes.json", "routes.json (contract:cli.proxy-routes v1)")
	out := fs.String("out", "/dynamic", "directory that receives dynamic.yml")
	ssl := fs.String("ssl", "/nself/ssl", "ssl/ directory (certificates/<dir>)")
	certRoot := fs.String("cert-root", "", "ssl/ as Traefik sees it (default --ssl)")
	helper := fs.String("helper", "http://traefik-acme:8080", "traefik-acme base URL")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	f, err := os.Open(*routes)
	if err != nil {
		fmt.Fprintln(errw, "render:", err)
		return 2
	}
	defer f.Close()
	m, err := contract.Load(f)
	if err != nil {
		fmt.Fprintln(errw, "render:", err)
		return 1
	}
	data, err := render.Render(m, render.Options{SSLRoot: *ssl, CertRoot: *certRoot, Helper: *helper})
	var ref *render.RefusalError
	if errors.As(err, &ref) {
		fmt.Fprintln(errw, ref.Error())
		return 1
	}
	if err != nil {
		fmt.Fprintln(errw, "render:", err)
		return 2
	}
	if err := writeAtomic(*out, "dynamic.yml", data); err != nil {
		fmt.Fprintln(errw, "render:", err)
		return 2
	}
	if err := writeAtomic(*out, ".nself-generated", []byte(marker)); err != nil {
		fmt.Fprintln(errw, "render:", err)
		return 2
	}
	return 0
}

func writeAtomic(dir, name string, data []byte) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, "."+name+".*.tmp")
	if err != nil {
		return err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), filepath.Join(dir, name))
}

func serve(args []string, errw io.Writer) int {
	fs := flag.NewFlagSet("serve-static", flag.ContinueOnError)
	fs.SetOutput(errw)
	root := fs.String("root", "/acme-webroot", "ACME webroot (read-only)")
	listen := fs.String("listen", ":8080", "listen address")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	srv := &http.Server{Addr: *listen, Handler: static.Handler(*root), ReadHeaderTimeout: 10 * time.Second}
	fmt.Fprintln(errw, "serve-static:", srv.ListenAndServe())
	return 2
}

// health is the traefik-acme container health check: GET /__nself/ok must answer 200.
func health(args []string, errw io.Writer) int {
	fs := flag.NewFlagSet("healthcheck", flag.ContinueOnError)
	fs.SetOutput(errw)
	addr := fs.String("addr", "127.0.0.1:8080", "serve-static address")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	c := http.Client{Timeout: 2 * time.Second}
	resp, err := c.Get("http://" + *addr + "/__nself/ok")
	if err != nil {
		fmt.Fprintln(errw, "healthcheck:", err)
		return 1
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		fmt.Fprintln(errw, "healthcheck: status", resp.StatusCode)
		return 1
	}
	return 0
}
