-- nself-claw: agent handoff queue (Y02 — P95)
-- Idempotent — CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS throughout.
--
-- np_agent_handoffs is an internal claw-plugin table. Not exposed via Hasura
-- Remote Schema at P95 (deferred to v1.2 admin orchestrator UI).
-- Multi-agent dequeue runtime also ships in v1.2; this migration creates the
-- queue so cron → claw.EnqueueHandoff() has a place to write at P95.

CREATE TABLE IF NOT EXISTS np_agent_handoffs (
    id              TEXT        PRIMARY KEY,          -- UUID, generated by EnqueueHandoff
    from_agent_id   TEXT        NOT NULL,             -- delegating agent ("cron" for scheduled jobs)
    to_agent_id     TEXT        NOT NULL,             -- target subagent
    session_id      TEXT,                             -- originating session (NULL for cron-triggered)
    context         JSONB,                            -- caller's working context
    tools           TEXT[]      NOT NULL DEFAULT '{}',-- tool subset being delegated
    permissions     JSONB       NOT NULL,             -- PermissionScope JSON blob
    timeout_seconds BIGINT      NOT NULL,             -- max wall-clock seconds for subagent
    return_to       TEXT,                             -- callback channel (NULL = fire-and-forget)
    status          TEXT        NOT NULL DEFAULT 'queued',  -- queued | running | done | timeout | error
    result          JSONB,                            -- subagent output (v1.2 runtime writes this)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    source_account_id TEXT NOT NULL DEFAULT 'primary'
);

CREATE INDEX IF NOT EXISTS idx_np_agent_handoffs_status
    ON np_agent_handoffs (status, created_at);

CREATE INDEX IF NOT EXISTS idx_np_agent_handoffs_to_agent
    ON np_agent_handoffs (to_agent_id, status);

COMMENT ON TABLE np_agent_handoffs IS
    'Queue of pending A→B agent delegation envelopes. Dequeue runtime ships v1.2.';
