#!/usr/bin/env bash
# assemble.sh [--check] [--dir DIR] [--out FILE] [--fixtures]: merge the per-owner fragments in images.d/
# into the generated images.json v1 (EPIC D12a, ADR 0030). Only this script writes images.json.
# Fragment: {"name","kind":"plugin|upstream|ci","image":"<repo>:<tag>@sha256:<64 hex>","platforms":[...],"owner"}
# or an array of them (images.d/plugins.json). Output keys are sorted, 2-space indent.
# Exit: 0 ok, 1 invalid fragment (named), duplicate name, or drift under --check, 2 usage.
set -eu
. "$(dirname "$0")/lib.sh"
img_need jq
dir=$IMG_ROOT/images.d; out=$IMG_ROOT/images.json; check=0; fixtures=0
while [ $# -gt 0 ]; do
  case $1 in
    --check) check=1; shift ;;
    --dir) dir=$2; shift 2 ;;
    --out) out=$2; shift 2 ;;
    --fixtures) fixtures=1; shift ;;
    *) echo "usage: assemble.sh [--check] [--dir DIR] [--out FILE] [--fixtures]" >&2; exit 2 ;;
  esac
done

# Validates one fragment and prints one {"f","e"} line per entry, or one {"f","err"} line per problem.
VALIDATE='
def bad:
  if type != "object" then "entry is not an object"
  elif ((.name | type) != "string") or (.name | test("^[A-Za-z0-9][A-Za-z0-9._/-]*$") | not) then "name must be a non-empty string of [A-Za-z0-9._/-]"
  elif ((.kind | type) != "string") or ((.kind | IN("plugin", "upstream", "ci")) | not) then "unknown kind \(.kind | tojson) (plugin|upstream|ci)"
  elif ((.image | type) != "string") or (.image | test("^[^@[:space:]]+:[^@:/[:space:]]+@sha256:[0-9a-f]{64}$") | not) then "image \(.image | tojson) must be <repository>:<tag>@sha256:<64 hex>"
  elif ((.platforms | type) != "array") or (.platforms | length) == 0 or (.platforms | all(type == "string" and test("^[a-z0-9]+/[a-z0-9]+(/[a-z0-9]+)?$")) | not) then "platforms must be a non-empty list like linux/amd64"
  elif ((.owner | type) != "string") or .owner == "" then "owner must be a non-empty string"
  else empty end;
(if type == "array" then .[] else . end) | (bad // "") as $b | if $b != "" then {f: $f, err: (.name? // "?" | tostring) + ": " + $b} else {f: $f, e: .} end'

assemble() {
  local f lines all="" rc=0 errs res
  for f in "$dir"/*.json; do
    [ -e "$f" ] || continue
    if ! lines=$(jq -c --arg f "$(basename "$f")" "$VALIDATE" "$f" 2>/dev/null); then
      echo "assemble: $(basename "$f"): not valid JSON" >&2; rc=1; continue
    fi
    all="$all$lines
"
  done
  errs=$(printf '%s' "$all" | jq -r 'select(has("err")) | "assemble: \(.f): \(.err)"')
  [ -z "$errs" ] || { printf '%s\n' "$errs" >&2; rc=1; }
  [ $rc = 0 ] || return 1
  res=$(printf '%s' "$all" | jq -S -s '
    ([group_by(.e.name)[] | select(length > 1)]) as $dups
    | if ($dups | length) > 0 then
        {dup: ($dups | map(.[0].e.name + " in " + (map(.f) | join(" and "))) | join("; "))}
      else
        {schema: "nself.plugins.images/v1",
         _generated: "GENERATED BY scripts/images/assemble.sh DO NOT HAND EDIT",
         images: (map({key: .e.name, value: (.e | {kind, image, platforms, owner})}) | from_entries)}
      end')
  if printf '%s' "$res" | jq -e 'has("dup")' >/dev/null; then
    echo "assemble: duplicate name $(printf '%s' "$res" | jq -r .dup)" >&2; return 1
  fi
  printf '%s\n' "$res"
}

if [ "$fixtures" = 1 ]; then
  t=$(img_tmp); trap 'rm -rf "$t"' EXIT; rc=0; td=$IMG_DIR/testdata/assemble
  ok() { echo "pass  $1"; }; no() { echo "FAIL  $1"; rc=1; }
  exit_code_of() { set +e; "$@" >"$t/stdout" 2>"$t/stderr"; echo $?; set -e; }
  c=$(exit_code_of bash "$0" --dir "$td/ok" --out "$t/images.json")
  [ "$c" = 0 ] && cmp -s "$t/images.json" "$td/golden.json" && ok "fixture fragments assemble byte-for-byte to the golden" || no "golden mismatch (rc=$c)"
  c=$(exit_code_of bash "$0" --check --dir "$td/ok" --out "$t/images.json"); [ "$c" = 0 ] && ok "--check passes on an assembled file" || no "--check failed on a fresh file (rc=$c)"
  neg() { # id fragment-name json expected-stderr-grep
    rm -rf "$t/n"; mkdir -p "$t/n"; cp "$td"/ok/*.json "$t/n/"; printf '%s\n' "$3" > "$t/n/$2"
    c=$(exit_code_of bash "$0" --dir "$t/n" --out "$t/n.out")
    if [ "$c" = 1 ] && grep -q "$4" "$t/stderr"; then ok "$1 exits 1 naming the fragment"; else no "$1: rc=$c stderr=$(cat "$t/stderr")"; fi
  }
  good='"kind":"upstream","platforms":["linux/amd64","linux/arm64"],"owner":"P7-TEST"'
  dig=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  neg duplicate-name dup.json "{\"name\":\"minio\",\"image\":\"nself/x:1@$dig\",$good}" 'dup.json\|duplicate name minio in'
  neg tag-without-digest nodigest.json "{\"name\":\"y\",\"image\":\"nself/y:1\",$good}" 'nodigest.json: y: image'
  neg digest-without-tag notag.json "{\"name\":\"y\",\"image\":\"nself/y@$dig\",$good}" 'notag.json: y: image'
  neg unknown-kind kind.json "{\"name\":\"y\",\"image\":\"nself/y:1@$dig\",\"kind\":\"weird\",\"platforms\":[\"linux/amd64\"],\"owner\":\"o\"}" 'kind.json: y: unknown kind'
  neg missing-owner owner.json "{\"name\":\"y\",\"image\":\"nself/y:1@$dig\",\"kind\":\"ci\",\"platforms\":[\"linux/amd64\"]}" 'owner.json: y: owner'
  neg malformed-json broken.json '{not json' 'broken.json'
  # stale lock: change a fragment without re-assembling
  rm -rf "$t/s"; mkdir -p "$t/s"; cp "$td"/ok/*.json "$t/s/"; cp "$t/images.json" "$t/s.json"
  sed -i.bak 's/P7-TEST-CI/P7-TEST-CI-2/' "$t/s/ci.json"; rm -f "$t/s/ci.json.bak"
  c=$(exit_code_of bash "$0" --check --dir "$t/s" --out "$t/s.json")
  [ "$c" = 1 ] && grep -q 'drift' "$t/stderr" && ok "--check exits 1 after a fragment changes without re-assembly" || no "stale lock not detected (rc=$c)"
  c=$(exit_code_of bash "$0" --check --dir "$t/s" --out "$t/missing.json"); [ "$c" = 1 ] && ok "--check exits 1 when images.json is missing" || no "missing images.json passed"
  mkdir -p "$t/e"; c=$(exit_code_of bash "$0" --dir "$t/e" --out "$t/e.json")
  [ "$c" = 0 ] && jq -e '.images == {}' "$t/e.json" >/dev/null && ok "no fragments assemble to images: {}" || no "empty assemble wrong (rc=$c)"
  exit $rc
fi

res=$(assemble) || { printf '%s\n' "$res" >&2; exit 1; }
if [ "$check" = 1 ]; then
  [ -f "$out" ] || { echo "assemble: drift: $out is missing; run scripts/images/assemble.sh" >&2; exit 1; }
  if printf '%s\n' "$res" | cmp -s - "$out"; then echo "assemble: $out is up to date"; exit 0; fi
  echo "assemble: drift: $out does not match $dir; run scripts/images/assemble.sh and commit" >&2; exit 1
fi
printf '%s\n' "$res" > "$out.tmp.$$" && mv "$out.tmp.$$" "$out"
echo "assemble: wrote $out ($(jq '.images | length' "$out") entries)"
