{{- range $name, $svc := .Values.services }}
{{- if eq $svc.kind "deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "nself.labels" (dict "root" $ "name" $name) | nindent 4 }}
spec:
  replicas: {{ default 1 $svc.replicas }}
  selector:
    matchLabels:
      {{- include "nself.selector" (dict "root" $ "name" $name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nself.labels" (dict "root" $ "name" $name) | nindent 8 }}
    spec:
      {{- include "nself.pod" (dict "root" $ "name" $name "svc" $svc "restart" "Always") | nindent 6 }}
{{- end }}
{{- end }}
