-- Down migration paired with 001_byok_tables.sql (P99 1.11 T07 autogenerated)
-- Rollback for 001_byok_tables.sql
-- Idempotent (IF EXISTS guards). Drops indexes before tables; tables before any
-- referenced parent. CASCADE not used — review if ON DELETE CASCADE side-effects
-- on np_tenants are desired.

DROP INDEX IF EXISTS idx_key_events_triggered;
DROP INDEX IF EXISTS idx_key_events_type;
DROP INDEX IF EXISTS idx_key_events_tenant;
DROP TABLE IF EXISTS np_encryption_key_events;

DROP INDEX IF EXISTS idx_enc_values_field;
DROP INDEX IF EXISTS idx_enc_values_record_group;
DROP INDEX IF EXISTS idx_enc_values_tenant;
DROP TABLE IF EXISTS np_encrypted_values;

DROP INDEX IF EXISTS idx_kms_configs_enabled;
DROP INDEX IF EXISTS idx_kms_configs_tenant;
DROP TABLE IF EXISTS np_kms_configs;
