#!/usr/bin/env python3
"""check-file-size.py: file-size ratchet, at most 300 lines per non-test source file.

Purpose
    Enforce the 300-line rule (APC P3/P4, final gate G11) in a repo with no Go
    root module, the way cli does with internal/repoqa/file_size_test.go and web
    does with eslint max-lines. Existing over-limit files are listed in a falling
    budget so they may not grow, and no new file may cross the limit.

Rule
    Counted: tracked files with extension .go .ts .tsx .js .mjs .py .rs .sh .astro.
    Not counted: any file under a vendor/, testdata/ or tests/ directory, files
    named *_test.go, *.test.* or *.spec.*, and generated files whose first 400
    bytes contain `GENERATED BY`. Symlinks and submodules are skipped.
    A line count is the number of newline-terminated lines plus a final
    unterminated one (what cli's bufio.Scanner counts), not `wc -l`.

Budget
    .github/file-size-budget.txt holds `<path><TAB><lines>`, one row per file over
    300 lines, sorted bytewise by path. The budget only falls:
      - an over-limit file that is not listed fails;
      - a listed file that grew fails;
      - a listed file that shrank (still over 300) fails until its row is lowered;
      - a listed file now at 300 or below, or gone, fails until its row is removed.
    The script never raises a count.

Modes
    (default)       check; one line per violation on stdout, exit 1 on any.
    --write-budget  create the budget from the current tree when the file does not
                    exist; otherwise only lower or drop rows. Refuses (exit 1, no
                    write) when a new over-limit file or a grown file exists.
    --list          print every over-limit file as `<path><TAB><lines>`, ignoring
                    the budget.

Inputs
    The Git index of the current directory (`git ls-files -z -s`) and blobs from
    `git cat-file --batch`. The working tree is never read for sources, so an
    untracked build output cannot trip the check. The budget file is read from the
    working tree at .github/file-size-budget.txt.

Outputs
    Violations: `<path>: <n> lines (limit 300)` for a new over-limit file,
    `<path>: <n> lines (budget <b>, limit 300)` for a grown file, and
    `<path>: stale budget row ...` for a row to lower or remove.
    Exit 0 clean, 1 violation or refused write, 2 git or budget-file failure.
"""
import os
import subprocess
import sys

LIMIT = 300
BUDGET = ".github/file-size-budget.txt"
EXTENSIONS = (".go", ".ts", ".tsx", ".js", ".mjs", ".py", ".rs", ".sh", ".astro")
SKIP_DIRS = ("vendor", "testdata", "tests")
GENERATED_MARK = b"GENERATED BY"
GENERATED_WINDOW = 400
CHUNK = 1 << 20


def is_candidate(path):
    """True when the path is a source file the rule counts (before GENERATED)."""
    if not path.endswith(EXTENSIONS):
        return False
    parts = path.split("/")
    if any(part in SKIP_DIRS for part in parts[:-1]):
        return False
    name = parts[-1]
    if name.endswith("_test.go") or ".test." in name or ".spec." in name:
        return False
    return True


class BlobReader:
    """Counts lines through one long-lived `git cat-file --batch`."""

    def __init__(self):
        self.proc = subprocess.Popen(["git", "cat-file", "--batch"],
                                     stdin=subprocess.PIPE, stdout=subprocess.PIPE)

    def scan(self, sha):
        """Return (line_count, first_bytes) for a blob."""
        self.proc.stdin.write(sha.encode() + b"\n")
        self.proc.stdin.flush()
        header = self.proc.stdout.readline().split()
        if len(header) != 3 or header[1] != b"blob":
            raise RuntimeError("git cat-file: no blob for " + sha)
        remaining = int(header[2])
        head = b""
        lines = 0
        last = b""
        while remaining > 0:
            data = self.proc.stdout.read(min(remaining, CHUNK))
            if not data:
                raise RuntimeError("git cat-file: short read for " + sha)
            remaining -= len(data)
            if len(head) < GENERATED_WINDOW:
                head += data[:GENERATED_WINDOW - len(head)]
            lines += data.count(b"\n")
            last = data[-1:]
        self.proc.stdout.read(1)  # trailing newline
        if last and last != b"\n":
            lines += 1
        return lines, head

    def close(self):
        self.proc.stdin.close()
        self.proc.wait()


def tracked_entries():
    """Yield (mode, sha, path) for every index entry, one per path."""
    out = subprocess.run(["git", "ls-files", "-z", "-s"], stdout=subprocess.PIPE,
                         check=True).stdout
    seen = set()
    for rec in out.split(b"\x00"):
        if not rec:
            continue
        meta, _, path = rec.partition(b"\t")
        mode, sha, _stage = meta.decode().split(" ")
        text = path.decode("utf-8", "surrogateescape")
        if text in seen:
            continue
        seen.add(text)
        yield mode, sha, text


def measure():
    """Return {path: lines} for every counted file in the index."""
    sizes = {}
    reader = BlobReader()
    try:
        for mode, sha, path in tracked_entries():
            if mode in ("160000", "120000") or not is_candidate(path):
                continue
            lines, head = reader.scan(sha)
            if GENERATED_MARK in head:
                continue
            sizes[path] = lines
    finally:
        reader.close()
    return sizes


def sort_key(path):
    return path.encode("utf-8", "surrogateescape")


def read_budget():
    """Return {path: lines}, or None when the budget file does not exist."""
    if not os.path.exists(BUDGET):
        return None
    rows = {}
    with open(BUDGET, "rb") as fh:
        for number, raw in enumerate(fh.read().split(b"\n"), 1):
            if not raw:
                continue
            path, tab, count = raw.decode("utf-8", "surrogateescape").partition("\t")
            if not tab or not count.isdigit() or not path or path in rows:
                raise ValueError("%s:%d: expected `<path><TAB><lines>`, unique path"
                                 % (BUDGET, number))
            rows[path] = int(count)
    return rows


def write_budget(rows):
    os.makedirs(os.path.dirname(BUDGET), exist_ok=True)
    body = "".join("%s\t%d\n" % (p, rows[p]) for p in sorted(rows, key=sort_key))
    with open(BUDGET, "wb") as fh:
        fh.write(body.encode("utf-8", "surrogateescape"))


def violations(sizes, budget):
    """Return (problems, lowered) where lowered is the budget the tree allows."""
    problems = []
    lowered = {}
    for path in sorted(sizes, key=sort_key):
        n = sizes[path]
        if n <= LIMIT:
            continue
        if path not in budget:
            problems.append("%s: %d lines (limit %d)" % (path, n, LIMIT))
        elif n > budget[path]:
            problems.append("%s: %d lines (budget %d, limit %d)"
                            % (path, n, budget[path], LIMIT))
        else:
            lowered[path] = n
            if n < budget[path]:
                problems.append("%s: stale budget row, now %d lines (budget %d); "
                                "lower the row to %d" % (path, n, budget[path], n))
    for path in sorted(budget, key=sort_key):
        if sizes.get(path, 0) <= LIMIT:
            state = ("%d lines" % sizes[path]) if path in sizes else "gone or not counted"
            problems.append("%s: stale budget row, %s (limit %d); remove the row"
                            % (path, state, LIMIT))
    return problems, lowered


def main(argv):
    modes = [a for a in argv if a in ("--write-budget", "--list")]
    if len(modes) != len(argv) or len(modes) > 1:
        print("usage: check-file-size.py [--write-budget | --list]", file=sys.stderr)
        return 2
    try:
        sizes = measure()
        budget = read_budget()
    except (subprocess.CalledProcessError, RuntimeError, OSError, ValueError) as err:
        print("check-file-size: %s" % err, file=sys.stderr)
        return 2

    if modes == ["--list"]:
        for path in sorted(sizes, key=sort_key):
            if sizes[path] > LIMIT:
                print("%s\t%d" % (path, sizes[path]))
        return 0

    if modes == ["--write-budget"]:
        if budget is None:
            write_budget({p: n for p, n in sizes.items() if n > LIMIT})
            return 0
        problems, lowered = violations(sizes, budget)
        refused = [p for p in problems if "stale budget row" not in p]
        if refused:
            print("\n".join(refused))
            print("check-file-size: refusing to raise or add a budget row",
                  file=sys.stderr)
            return 1
        write_budget(lowered)
        return 0

    problems, _ = violations(sizes, budget or {})
    if problems:
        print("\n".join(problems))
        print("check-file-size: %d violation%s; split the file or lower the budget "
              "(the budget never rises)" % (len(problems), "" if len(problems) == 1 else "s"),
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
