// Package nginx manages per-project Nginx virtual host configuration.
// Vhosts are written to a single generated conf file and reloaded atomically.
// The file is regenerated in full on every add/remove to maintain consistency.
package nginx

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"sort"
	"strings"
	"text/template"
	"time"
)

// Client manages the Nginx vhost config file.
type Client struct {
	confPath string
}

// NewClient creates a Nginx client targeting the given conf file path.
func NewClient(confPath string) *Client {
	return &Client{confPath: confPath}
}

// VhostInput holds parameters for a single project's virtual host.
type VhostInput struct {
	Slug       string
	Domain     string
	HasuraPort int
	BaseDomain string
}

// vhostEntry is the in-memory representation of one vhost.
type vhostEntry struct {
	Slug       string
	Domain     string
	HasuraPort int
}

// AddVhost adds a new vhost to the config file.
// Reads existing entries, appends the new one, and rewrites the file atomically.
func (c *Client) AddVhost(ctx context.Context, input VhostInput) error {
	entries, err := c.readEntries()
	if err != nil {
		return err
	}

	// Check for duplicate.
	for _, e := range entries {
		if e.Slug == input.Slug {
			slog.Info("nginx: vhost already exists, updating", "slug", input.Slug)
			// Remove and re-add to update domain/port.
			entries = removeEntry(entries, input.Slug)
			break
		}
	}

	entries = append(entries, vhostEntry{
		Slug:       input.Slug,
		Domain:     input.Domain,
		HasuraPort: input.HasuraPort,
	})
	sort.Slice(entries, func(i, j int) bool { return entries[i].Slug < entries[j].Slug })

	return c.writeEntries(entries)
}

// RemoveVhost removes a project's vhost from the config file.
func (c *Client) RemoveVhost(ctx context.Context, slug string) error {
	entries, err := c.readEntries()
	if err != nil {
		return err
	}
	entries = removeEntry(entries, slug)
	return c.writeEntries(entries)
}

// Reload signals Nginx to reload its configuration atomically (nginx -s reload).
// Returns an error if the reload fails.
func (c *Client) Reload(ctx context.Context) error {
	start := time.Now()
	cmd := exec.CommandContext(ctx, "nginx", "-s", "reload")
	out, err := cmd.CombinedOutput()
	latencyMs := time.Since(start).Milliseconds()
	if err != nil {
		return fmt.Errorf("nginx -s reload: %w (output: %s, latency_ms: %d)", err, strings.TrimSpace(string(out)), latencyMs)
	}
	slog.Info("nginx reload ok", "latency_ms", latencyMs)
	return nil
}

// vhostTemplate is the Nginx server block template for a single project.
var vhostTemplate = template.Must(template.New("vhost").Parse(`
# Generated by nself tenant-controller — DO NOT HAND EDIT
# Project: {{.Slug}}
server {
    listen 443 ssl;
    server_name {{.Domain}};

    location /v1/graphql {
        proxy_pass http://127.0.0.1:{{.HasuraPort}}/v1/graphql;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Hasura-Project-Slug "{{.Slug}}";
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /v1/graphql/websocket {
        proxy_pass http://127.0.0.1:{{.HasuraPort}}/v1/graphql;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Hasura-Project-Slug "{{.Slug}}";
    }

    location / {
        proxy_pass http://127.0.0.1:{{.HasuraPort}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Hasura-Project-Slug "{{.Slug}}";
    }
}
`))

// readEntries parses the existing conf file to extract current vhost entries.
// Returns empty slice if the file does not exist.
func (c *Client) readEntries() ([]vhostEntry, error) {
	data, err := os.ReadFile(c.confPath)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read nginx conf: %w", err)
	}

	// Parse: extract slug + domain + port from "# Project: <slug>" + "server_name" + "proxy_pass" lines.
	var entries []vhostEntry
	lines := strings.Split(string(data), "\n")
	var cur vhostEntry
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "# Project: ") {
			cur = vhostEntry{Slug: strings.TrimPrefix(line, "# Project: ")}
		}
		if strings.HasPrefix(line, "server_name ") && cur.Slug != "" {
			cur.Domain = strings.TrimSuffix(strings.TrimPrefix(line, "server_name "), ";")
		}
		if strings.Contains(line, "proxy_pass http://127.0.0.1:") && strings.Contains(line, "/v1/graphql;") && cur.Slug != "" {
			portStr := strings.TrimPrefix(line, "proxy_pass http://127.0.0.1:")
			portStr = strings.TrimSuffix(portStr, "/v1/graphql;")
			var port int
			if _, err := fmt.Sscanf(portStr, "%d", &port); err == nil {
				cur.HasuraPort = port
				entries = append(entries, cur)
				cur = vhostEntry{}
			}
		}
	}
	return entries, nil
}

// writeEntries rewrites the conf file with all current entries atomically.
func (c *Client) writeEntries(entries []vhostEntry) error {
	var sb strings.Builder
	sb.WriteString("# nself-projects.conf — generated by tenant-controller\n")
	sb.WriteString("# DO NOT HAND EDIT — managed automatically\n\n")

	for _, e := range entries {
		if err := vhostTemplate.Execute(&sb, e); err != nil {
			return fmt.Errorf("render vhost template for %s: %w", e.Slug, err)
		}
	}

	// Write atomically: temp file then rename.
	tmpPath := c.confPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("write nginx conf tmp: %w", err)
	}
	if err := os.Rename(tmpPath, c.confPath); err != nil {
		return fmt.Errorf("rename nginx conf: %w", err)
	}
	return nil
}

func removeEntry(entries []vhostEntry, slug string) []vhostEntry {
	out := entries[:0]
	for _, e := range entries {
		if e.Slug != slug {
			out = append(out, e)
		}
	}
	return out
}
