// Purpose: the output schema of `nself k8s values`: the values.yaml document
// (everything except env values) and the secrets.yaml document (every env
// value). The chart in charts/nself renders these two files and nothing else.
//
// Inputs: none (type definitions only).
//
// Outputs: Values, Secrets and their parts; Kind constants.
//
// Constraints: values.yaml carries env NAMES only; secrets.yaml carries every
// env VALUE. Field order here is the emitted order; maps are emitted with
// sorted keys, so the output is byte-stable.
package values

// Service kinds. The chart picks the workload template by this field.
const (
	KindDeployment  = "deployment"
	KindStatefulSet = "statefulset"
	KindJob         = "job"
	// KindIngress marks the compose nginx service: it is not deployed, its
	// routes become Ingress rules (Values.Ingress).
	KindIngress = "ingress"
)

// GeneratedMarker is the first line of every generated file.
const GeneratedMarker = "# GENERATED BY nself k8s values - DO NOT HAND EDIT"

// Values is the document written to .nself/generated/k8s/values.yaml.
type Values struct {
	Project       string             `yaml:"project"`
	Services      map[string]Service `yaml:"services"`
	Volumes       map[string]Volume  `yaml:"volumes,omitempty"`
	Ingress       Ingress            `yaml:"ingress"`
	Unsupported   []Unsupported      `yaml:"unsupported"`
	UnmappedRoute []Unsupported      `yaml:"unmappedRoutes"`
}

// Service is one compose service projected to a workload.
type Service struct {
	Kind       string   `yaml:"kind"`
	Image      string   `yaml:"image"`
	Tag        string   `yaml:"tag,omitempty"`
	Digest     string   `yaml:"digest,omitempty"`
	Entrypoint []string `yaml:"entrypoint,omitempty"`
	Command    []string `yaml:"command,omitempty"`
	Env        []string `yaml:"env,omitempty"`
	Ports      []Port   `yaml:"ports,omitempty"`
	Mounts     []Mount  `yaml:"mounts,omitempty"`
	Probe      *Probe   `yaml:"probe,omitempty"`
	NotMapped  []string `yaml:"notMapped,omitempty"`
}

// Port is a container port (compose "target"); published ports do not exist
// in a cluster.
type Port struct {
	Port     int    `yaml:"port"`
	Protocol string `yaml:"protocol"`
}

// Mount attaches a named volume (Volumes key) to a path.
type Mount struct {
	Volume   string `yaml:"volume"`
	Path     string `yaml:"path"`
	ReadOnly bool   `yaml:"readOnly,omitempty"`
}

// Volume is a named compose volume, rendered as a PersistentVolumeClaim.
type Volume struct {
	Claim string `yaml:"claim"`
}

// Probe is a compose healthcheck as an exec readiness probe.
type Probe struct {
	Exec         []string `yaml:"exec"`
	PeriodS      int      `yaml:"periodSeconds"`
	TimeoutS     int      `yaml:"timeoutSeconds"`
	Retries      int      `yaml:"failureThreshold"`
	StartPeriodS int      `yaml:"initialDelaySeconds"`
}

// Ingress holds the Ingress rules built from the nginx routes.
type Ingress struct {
	Rules []Rule `yaml:"rules"`
}

// Rule is one host routed to one in-cluster Service.
type Rule struct {
	Name    string `yaml:"name"`
	Host    string `yaml:"host"`
	Service string `yaml:"service"`
	Port    int    `yaml:"port"`
	Scheme  string `yaml:"scheme"`
}

// Unsupported names something that has no k8s mapping, with the reason.
type Unsupported struct {
	Name   string `yaml:"name"`
	Reason string `yaml:"reason"`
}

// Secrets is the document written to .nself/generated/k8s/secrets.yaml
// (mode 0600): service name -> env name -> value.
type Secrets struct {
	Secrets map[string]map[string]string `yaml:"secrets"`
}
