// Purpose: subcommands for the WAF plugin (enable, mode, report), moved
// verbatim from the core CLI's cmd/commands/waf.go under CLI-R11. Behavior
// and flags are unchanged; only the package name, root-command wiring
// (root.go), and the internal/config + internal/ui replacements
// (internal/projectroot + internal/tui) changed.
//
// Inputs: cobra flags per subcommand; the current working directory (to
// locate the nSelf project root); the running docker compose stack for
// `report`.
//
// Outputs: writes nginx/waf/{coraza,custom}.conf under the project root,
// edits coraza.conf's SecRuleEngine directive, or prints recent WAF audit
// log lines.
//
// Constraints: no dependency on the core CLI's internal/* packages.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/nself-org/nself-waf/internal/projectroot"
	"github.com/nself-org/nself-waf/internal/tui"
)

var wafEnableCmd = &cobra.Command{
	Use:   "enable",
	Short: "Enable the WAF in detection mode",
	Long: `Enable the Coraza WAF with OWASP Core Rule Set in DetectionOnly mode.
Requests are logged but not blocked. Use 'nself waf mode blocking' to enforce.`,
	RunE: runWAFEnable,
}

var wafModeCmd = &cobra.Command{
	Use:   "mode <detection|blocking>",
	Short: "Set WAF enforcement mode",
	Long: `Switch the WAF between detection (log only) and blocking (enforce) mode.

  detection  — log suspicious requests but allow them through
  blocking   — block requests matching OWASP CRS rules`,
	Args: cobra.ExactArgs(1),
	RunE: runWAFMode,
}

var wafReportCmd = &cobra.Command{
	Use:   "report",
	Short: "Show recent WAF events",
	Long: `Display recent WAF events from nginx error logs.

Use --since to filter by time window (default: 24h).`,
	RunE: runWAFReport,
}

func init() {
	wafReportCmd.Flags().String("since", "24h", "Time window for report (e.g., 1h, 24h, 7d)")
}

func runWAFEnable(cmd *cobra.Command, args []string) error {
	tui.CommandHeader("nself waf enable", "Enable WAF (Coraza + OWASP CRS)")

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}
	workdir, err := projectroot.FindNSelfRoot(cwd)
	if err != nil {
		return fmt.Errorf("no nself project found: run 'nself init' first")
	}

	// Create WAF directories.
	wafDir := filepath.Join(workdir, "nginx", "waf")
	crsDir := filepath.Join(wafDir, "crs")
	for _, d := range []string{wafDir, crsDir} {
		if mkErr := os.MkdirAll(d, 0755); mkErr != nil {
			return fmt.Errorf("creating WAF directory %s: %w", d, mkErr)
		}
	}

	// Write Coraza main config.
	corazaConf := `# Coraza WAF Configuration
# Generated by nself waf enable

SecRuleEngine DetectionOnly
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecResponseBodyAccess Off

# OWASP CRS
Include /etc/nginx/waf/crs/*.conf

# Custom rules
Include /etc/nginx/waf/custom.conf

# Logging — waf_event label for Loki
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogType Serial
SecAuditLog /var/log/nginx/waf_audit.log
`
	corazaPath := filepath.Join(wafDir, "coraza.conf")
	if err := os.WriteFile(corazaPath, []byte(corazaConf), 0644); err != nil {
		return fmt.Errorf("writing coraza.conf: %w", err)
	}

	// Write empty custom rules file.
	customPath := filepath.Join(wafDir, "custom.conf")
	if _, err := os.Stat(customPath); os.IsNotExist(err) {
		custom := "# Custom WAF rules\n# Add rules here to extend or override OWASP CRS\n"
		if err := os.WriteFile(customPath, []byte(custom), 0644); err != nil {
			return fmt.Errorf("writing custom.conf: %w", err)
		}
	}

	tui.Success("WAF enabled in DetectionOnly mode.")
	tui.Info("WAF config: nginx/waf/coraza.conf")
	tui.Info("Custom rules: nginx/waf/custom.conf")
	tui.Info("Run 'nself build && nself restart nginx' to apply.")
	tui.Info("Use 'nself waf mode blocking' to enforce rules.")
	return nil
}

func runWAFMode(cmd *cobra.Command, args []string) error {
	mode := strings.ToLower(args[0])
	if mode != "detection" && mode != "blocking" {
		return fmt.Errorf("invalid mode %q: use 'detection' or 'blocking'", mode)
	}

	tui.CommandHeader("nself waf mode", fmt.Sprintf("Set WAF mode to %s", mode))

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}
	workdir, err := projectroot.FindNSelfRoot(cwd)
	if err != nil {
		return fmt.Errorf("no nself project found")
	}

	corazaPath := filepath.Join(workdir, "nginx", "waf", "coraza.conf")
	data, err := os.ReadFile(corazaPath)
	if err != nil {
		return fmt.Errorf("reading coraza.conf: %w (run 'nself waf enable' first)", err)
	}

	content := string(data)
	var oldMode, newMode string
	if mode == "blocking" {
		oldMode = "SecRuleEngine DetectionOnly"
		newMode = "SecRuleEngine On"
	} else {
		oldMode = "SecRuleEngine On"
		newMode = "SecRuleEngine DetectionOnly"
	}

	if !strings.Contains(content, oldMode) {
		if strings.Contains(content, newMode) {
			tui.Info(fmt.Sprintf("WAF is already in %s mode.", mode))
			return nil
		}
		return fmt.Errorf("could not find SecRuleEngine directive in coraza.conf")
	}

	content = strings.Replace(content, oldMode, newMode, 1)
	if err := os.WriteFile(corazaPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing coraza.conf: %w", err)
	}

	tui.Success(fmt.Sprintf("WAF mode set to %s.", mode))
	tui.Info("Run 'nself restart nginx' to apply.")
	return nil
}

func runWAFReport(cmd *cobra.Command, args []string) error {
	since, _ := cmd.Flags().GetString("since")

	tui.CommandHeader("nself waf report", fmt.Sprintf("WAF events (last %s)", since))

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}
	workdir, err := projectroot.FindNSelfRoot(cwd)
	if err != nil {
		return fmt.Errorf("no nself project found")
	}

	// Try to read WAF audit log from the nginx container.
	logCmd := exec.Command("docker", "compose", "exec", "nginx",
		"sh", "-c", "cat /var/log/nginx/waf_audit.log 2>/dev/null || echo 'No WAF audit log found'")
	logCmd.Dir = workdir
	logCmd.Stdout = os.Stdout
	logCmd.Stderr = os.Stderr
	if err := logCmd.Run(); err != nil {
		tui.Warn("Could not read WAF audit log. Is the WAF enabled?")
		return nil
	}

	return nil
}
