location /plugins/post/ {
    set $upstream_post 127.0.0.1:3129;
    proxy_pass http://$upstream_post/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 120s;
    proxy_connect_timeout 30s;
}
