-- Down migration paired with 001_warehouse_tracking.sql (P99 1.11 T07 autogenerated)
-- Rollback for warehouse G01 tracking tables
-- Idempotent (IF EXISTS guards).

DROP INDEX IF EXISTS np_warehouse_errors_occurred_at_idx;
DROP TABLE IF EXISTS np_warehouse_errors;
DROP TABLE IF EXISTS np_warehouse_watermarks;
