#cloud-config
# nSelf server bootstrap — generated by Terraform templatefile().
# Template vars: domain, nself_version, backup_destination
#
# Purpose:   Provision a hardened Ubuntu 22.04 host ready for 'nself start'.
# Inputs:    domain (string), nself_version (string), backup_destination (string)
# Outputs:   Running Docker CE + compose, UFW+fail2ban active, swap enabled, deploy user ready.
# Constraints: Runs once at first boot via cloud-init. Idempotent commands only.
# SPORT:     Hetzner server provisioning — F08-SERVICE-INVENTORY.md

hostname: ${domain}
manage_etc_hosts: true

# ---------------------------------------------------------------------------
# Packages installed via apt before runcmd executes.
# Docker CE is installed via runcmd (requires apt-key + custom repo first).
# ---------------------------------------------------------------------------
packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - sudo
  # build-essential (make + gcc) + zip/unzip: required by self-hosted GitHub Actions
  # runners for `make dist` at release time (Go cross-build + Windows .zip packaging).
  # Absent from the base Ubuntu image; a missing `make` then a missing `zip` broke
  # nself-org/cli release.yml on nself-sentry (2026-07-01). Installing them here means
  # every provisioned box (app + sentry/runner) has them from first boot.
  - build-essential
  - zip
  - unzip

package_update: true
package_upgrade: true

# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------
users:
  - name: nself
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    lock_passwd: true

# ---------------------------------------------------------------------------
# Written files (config, not secrets)
# ---------------------------------------------------------------------------
write_files:
  # fail2ban: enable sshd jail
  - path: /etc/fail2ban/jail.local
    owner: root:root
    permissions: "0644"
    content: |
      [DEFAULT]
      bantime  = 3600
      findtime = 600
      maxretry = 5
      backend  = systemd

      [sshd]
      enabled  = true
      port     = 22
      filter   = sshd
      logpath  = /var/log/auth.log

  # unattended-upgrades: security updates only
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root:root
    permissions: "0644"
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "$${distro_id}:$${distro_codename}-security";
      };
      Unattended-Upgrade::AutoFixInterruptedDpkg "true";
      Unattended-Upgrade::MinimalSteps "true";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "false";

  - path: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root:root
    permissions: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

  # Placeholder for nSelf deploy metadata — written by 'nself deploy' later.
  - path: /home/nself/app/.nself-deploy
    owner: nself:nself
    permissions: "0600"
    content: |
      domain=${domain}
      nself_version=${nself_version}
      backup_destination=${backup_destination}
%{ if deploy_ssh_pubkey != "" }
  - path: /home/nself/.ssh/authorized_keys
    owner: nself:nself
    permissions: '0600'
    content: |
      ${deploy_ssh_pubkey}
%{ endif }

# ---------------------------------------------------------------------------
# Sequential run commands
# ---------------------------------------------------------------------------
runcmd:
  # -- Docker CE (stable channel, apt method) --------------------------------
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
      > /etc/apt/sources.list.d/docker.list
  - apt-get update -qq
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker

  # -- GitHub CLI (gh) -------------------------------------------------------
  # Self-hosted GitHub Actions runners rely on `gh` (GitHub-hosted runners ship
  # it). nself-org/cli release.yml uses `gh api` for the Homebrew lockstep gate;
  # a missing gh failed that gate on nself-sentry (2026-07-01). Install via the
  # official apt repo so every provisioned box has it.
  - curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg -o /etc/apt/keyrings/githubcli-archive-keyring.gpg
  - chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
  - |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] \
      https://cli.github.com/packages stable main" \
      > /etc/apt/sources.list.d/github-cli.list
  - apt-get update -qq
  - apt-get install -y gh

  # -- Swap (2 GB) -----------------------------------------------------------
  - |
    if [ ! -f /swapfile ]; then
      dd if=/dev/zero of=/swapfile bs=1M count=2048
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi

  # -- Deploy directory ------------------------------------------------------
  - mkdir -p /home/nself/app
  - chown -R nself:nself /home/nself/app
  - chmod 750 /home/nself/app

  # -- SSH authorized_keys for deploy user -----------------------------------
  # The nself Hetzner SSH key is injected via hcloud_server.ssh_keys (cloud platform
  # handles key injection for root). For the nself deploy user, operators run:
  #   nself ops profile sync --target <name>
  # which calls 'nself ops ssh-copy-id' post-provision. No plaintext pubkey here.
  - mkdir -p /home/nself/.ssh
  - chmod 700 /home/nself/.ssh
  - touch /home/nself/.ssh/authorized_keys
  - chmod 600 /home/nself/.ssh/authorized_keys
  - chown -R nself:nself /home/nself/.ssh

  # -- UFW -------------------------------------------------------------------
  - ufw --force reset
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp comment 'SSH'
  - ufw allow 80/tcp comment 'HTTP'
  - ufw allow 443/tcp comment 'HTTPS'
  - ufw --force enable

  # -- fail2ban --------------------------------------------------------------
  - systemctl enable --now fail2ban

  # -- unattended-upgrades ---------------------------------------------------
  - systemctl enable unattended-upgrades
  - systemctl start unattended-upgrades

  # -- nSelf version marker --------------------------------------------------
  - echo "${nself_version}" > /home/nself/.nself-version
  - chown nself:nself /home/nself/.nself-version

final_message: |
  nSelf server for ${domain} (v${nself_version}) is ready.
  Docker CE, UFW, fail2ban, swap, and deploy user configured.
  Run 'nself ops profile sync' to push secrets and start services.
