// Package contract holds the plugin's own copy of contract:cli.proxy-routes v1
// (the routes.json that `nself build` writes). The plugin never imports cli
// packages: it reads this file and nothing else (ADR 0027).
//
// Inputs: a routes.json byte stream. Outputs: Model. Constraints: field names
// and meaning follow the contract; additive v1 fields the renderer does not know
// are ignored by Load, and every field below is either rendered or refused.
package contract

import (
	"encoding/json"
	"fmt"
	"io"
)

// Marker is the first key's value of every routes.json.
const Marker = "GENERATED BY nself build - DO NOT HAND EDIT"

type Model struct {
	Generated        string        `json:"_generated"`
	SchemaVersion    string        `json:"schema_version"`
	Project          string        `json:"project"`
	Env              string        `json:"env"`
	BaseDomain       string        `json:"base_domain"`
	Defaults         Defaults      `json:"defaults"`
	DefaultServer    DefaultServer `json:"default_server"`
	UnmodelledGlobal []string      `json:"unmodelled_global"`
	Zones            []Zone        `json:"zones"`
	Routes           []Route       `json:"routes"`
}

type Defaults struct {
	MaxBodyBytes int64 `json:"max_body_bytes"`
	Gzip         struct {
		Enabled   bool     `json:"enabled"`
		Types     []string `json:"types"`
		MinLength *int     `json:"min_length"`
	} `json:"gzip"`
	TLS struct {
		Protocols []string `json:"protocols"`
		Ciphers   *string  `json:"ciphers"`
	} `json:"tls"`
	ServerTokens bool `json:"server_tokens"`
}

type DefaultServer struct {
	HTTP struct {
		ACMEWebroot   *string `json:"acme_webroot"`
		HealthPath    *string `json:"health_path"`
		RedirectHTTPS bool    `json:"redirect_https"`
	} `json:"http"`
	HTTPS struct {
		Action string `json:"action"`
	} `json:"https"`
}

type Zone struct {
	Name string  `json:"name"`
	Kind string  `json:"kind"`
	Key  string  `json:"key"`
	Rate *string `json:"rate"`
}

type Route struct {
	ID          string   `json:"id"`
	Source      string   `json:"source"`
	Owner       *string  `json:"owner"`
	File        string   `json:"file"`
	ServerNames []string `json:"server_names"`
	Listen      struct {
		HTTP  bool `json:"http"`
		HTTPS bool `json:"https"`
	} `json:"listen"`
	TLS                 *RouteTLS         `json:"tls"`
	HTTPToHTTPSRedirect bool              `json:"http_to_https_redirect"`
	SecurityHeaders     map[string]string `json:"security_headers"`
	BlockedPaths        []BlockedPath     `json:"blocked_paths"`
	RateLimit           *RateLimit        `json:"rate_limit"`
	Locations           []Location        `json:"locations"`
	ShadowedBy          *string           `json:"shadowed_by"`
	Unmodelled          []string          `json:"unmodelled"`
}

type RouteTLS struct {
	SSLDir          string   `json:"ssl_dir"`
	HasTrustedChain bool     `json:"has_trusted_chain"`
	Protocols       []string `json:"protocols"`
	Ciphers         *string  `json:"ciphers"`
}

type BlockedPath struct {
	Regex  string `json:"regex"`
	Status int    `json:"status"`
}

type RateLimit struct {
	Zone      string `json:"zone"`
	Burst     int    `json:"burst"`
	ConnLimit int    `json:"conn_limit"`
}

type Location struct {
	Path     string `json:"path"`
	Match    string `json:"match"`
	Upstream *struct {
		Scheme string `json:"scheme"`
		Host   string `json:"host"`
		Port   int    `json:"port"`
	} `json:"upstream"`
	RateLimit *struct {
		Zone    string `json:"zone"`
		Burst   int    `json:"burst"`
		Nodelay bool   `json:"nodelay"`
	} `json:"rate_limit"`
	WebSocket        bool              `json:"websocket"`
	ForwardedHeaders bool              `json:"forwarded_headers"`
	HeadersSet       map[string]string `json:"headers_set"`
	Timeouts         struct {
		ConnectS *int `json:"connect_s"`
		ReadS    *int `json:"read_s"`
		SendS    *int `json:"send_s"`
	} `json:"timeouts"`
	MaxBodyBytes *int64   `json:"max_body_bytes"`
	AccessLog    bool     `json:"access_log"`
	DenyAll      bool     `json:"deny_all"`
	Methods      []string `json:"methods"`
	Return       *struct {
		Status int     `json:"status"`
		To     *string `json:"to"`
	} `json:"return"`
	StaticRoot  *string `json:"static_root"`
	HealthProbe bool    `json:"health_probe"`
}

// Load decodes and sanity-checks a routes.json.
func Load(r io.Reader) (*Model, error) {
	var m Model
	if err := json.NewDecoder(r).Decode(&m); err != nil {
		return nil, fmt.Errorf("routes.json: %w", err)
	}
	if m.Generated != Marker {
		return nil, fmt.Errorf("routes.json: missing the generated marker")
	}
	if m.SchemaVersion != "1" {
		return nil, fmt.Errorf("routes.json: schema_version %q, this renderer reads \"1\"", m.SchemaVersion)
	}
	return &m, nil
}
